= Veeva Vault Connector Release Notes - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Veeva Vault (Veeva Vault) enables you to integrate the Veeva Vault platform with third party vendors using connector operations in a Mule flow. The connector performs CRUD (Create, Retrieve, Update, Delete), Query, and Export operations on the vault using Veeva Vault APIs.

=== *1.2.0*

April 2020

=== *Compatibility*

[cols=",",options="header",]
|===
|*App/Service* |*Version*
|Mule |4.1 and later
|Anypoint Studio |7.0 and later
|JDK |1.8 and later 
|Veeva Vault APIs |18.0 and later 
|Apache Common Language |2.6 and later 
|JSON libraries |20170516 and later 
|===

==== *New Features*

* OAuth2 Authentication connection option is added in connector configuration.
* Invoke Rest API operation added that enables to invoke Veeva Vault Rest APIs.

==== *Fixed Issues*

* Export documents operation runs into infinite loop when invalid/deleted document id is passed. This has been fixed.

=== *1.1.0*

February 5 2020

==== *Compatibility*

[cols=",",options="header",]
|===
|*App/Service* |*Version*
|Mule |4.1 and later
|Anypoint Studio |7.0 and later
|JDK |1.8 and later 
|Veeva Vault APIs |18.0 and later 
|Apache Common Language |2.6 and later 
|JSON libraries |20170516 and later 
|===

==== *New Features*

* The Spark Message Validator operation was implemented to validate and verify Spark messages with a public key and signature received from the vault.

==== *Fixed Issues*

This release contains the following fixed issues:

* Export Documents operation should return Job results instead of Job Status response.
* Get Documents and Get Object Records operations throws an error when Document/Field properties list configured as empty or None.

=== *1.0.3*

August 2019

This is a new release.

